version: "3.8"
#docker engine version
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # host.docker.internal: 도커 컨테이너에서 호스트 머신에 접근하기 위한 특별한 DNS 이름
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/yourdb
      # 또는 실제 외부 DB 주소
      # - SPRING_DATASOURCE_URL=jdbc:mysql://your-actual-db-host:3306/yourdb
      - SPRING_DATASOURCE_USERNAME=your_username
      - SPRING_DATASOURCE_PASSWORD=your_password