
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/back
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_slq: true


logging.level:
  org.hibernate.orm.jdbc.bind: trace
