spring:
  datasource:
    url: jdbc:mysql://database-1.cn0gu4wqaabh.ap-northeast-2.rds.amazonaws.com:3306/testdb?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: gjwlswls
  sql:
    init:
      mode: always
  jpa:

    #hibernate:
    #  ddl-auto: update

    #이유 찾아보기
    #https://giron.tistory.com/128
    properties:
      hibernate.hbm2ddl.auto: create-drop
      #이유 찾아보기
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

logging:
  level:
    demo_book: DEBUG

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #해시 변환된 값은 복호화 못하는듯
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
  #86400 -> 시간 값