spring:
  profiles:
    active: dev
---
# dev 에만 적용되는 설정
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    demo_book: DEBUG

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400