#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/newdb?useSSL=true&serverTimezone=Asia/Seoul
#    driver-class-name: com.mysql.cj.jdbc.Driver
##    username: admin
##    password: gjwlswls
#    username: root
#    password: 1234
#
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#
#    #이유 찾아보기
#    properties:
#      #이유 찾아보기
#      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#      hibernate:
#        format_sql: true
#        show_sql: true
#    defer-datasource-initialization: true
