#
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/back
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver



#mysql 용   나중에 다시 수정해서 사용하기
#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/view/
#      suffix: .jsp
#  datasource:
#    url:jdbc:mysql://localhost:3306/banck2//나중에 다시 바꾸기
#    driver-class-name:
#    username:
#    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_slq: true


logging.level:
  org.hibernate.orm.jdbc.bind: trace
